name: Build and upload jar binary as artifact

on:
  push:
    branches:
      - master
      - artifact_push_action

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Build and package
        run: |
          ./gradlew build

      - name: Java application binary
        uses: actions/upload-artifact@v4
        with:
          path: ./app/build/libs/app-*.jar
          if-no-files-found: error
